project:
  type: book

book:
  title: "Geoinformática"
  author: "Pablo López-Ramírez"
  date: "2023-1-4"
  chapters:
    - index.qmd
    - intro.qmd
    - part: parte_1.qmd
      chapters:
        - parte_1/01_transformacion.ipynb
        - parte_1/02_ejemplo_transformacion.ipynb
        - parte_1/03_automatizacion_transformacion.ipynb
        - parte_1/04_visualizacion_covid_1.ipynb
        - parte_1/05_intro_geopandas.ipynb
        - parte_1/06_manipulacion_espacial.ipynb
        - parte_1/07_mapas_COVID.ipynb
    - part: parte_2.qmd
      chapters:
        - parte_2/intro_R.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

execute:
  freeze: auto
