project:
  type: book

book:
  title: "Geoinformática"
  author: "Pablo López-Ramírez"
  date: "2023-1-4"
  chapters:
    - index.qmd
    - intro.qmd
    - part: parte_1.qmd
      chapters:
        - parte_1/prueba.ipynb
    - part: parte_2.qmd
      chapters:
        - parte_2/intro_R.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

execute:
  freeze: auto
